default_install_hook_types: [pre-commit, pre-push]
fail_fast: true

repos:
  - repo: local
    hooks:
      - id: pylint-boolean-naming
        name: pylint-boolean-naming
        entry: pylint
        language: system
        stages: [commit]
